## Introduction to data analysis

In [4]:
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import mailbox

In [5]:
iris_df = sns.load_dataset("iris")

In [6]:
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
!dir

 Volume in drive C has no label.
 Volume Serial Number is F423-6A5D

 Directory of C:\Users\USER\Desktop\Data Science\my notebooks

08/06/2025  01:30 PM    <DIR>          .
08/06/2025  01:30 PM    <DIR>          ..
08/06/2025  12:25 PM    <DIR>          .ipynb_checkpoints
07/23/2025  12:08 PM            23,806 21-07-25 Conditional Statements in Python.ipynb
07/29/2025  11:12 PM            24,814 28-07-25 for loops.ipynb
07/30/2025  02:02 PM       284,536,461 All mail Including Spam and Trash.mbox
06/18/2025  01:45 PM           256,729 archive.zip
07/15/2025  03:34 PM            17,572 Assignment(14th july).ipynb
06/25/2025  12:34 PM             7,556 assignmentOne.ipynb
07/28/2025  04:36 PM         1,241,150 backup_20250728.csv
07/26/2025  04:35 PM             7,558 cleaned_data.csv
07/26/2025  05:00 PM             7,172 Code notes.ipynb
07/13/2025  11:28 AM           459,639 Coffee Tea and Beverages.csv
07/04/2025  05:36 PM                14 example.txt
07/02/2025  12:37 PM           481,250 finance_economics_dataset (1).csv
06/28/2020  11:32 AM         2,501,007 Fintech_user.csv
07/28/2025  08:04 PM           561,171 Fintech_user.ipynb
08/04/2025  01:05 PM         1,143,342 Fintech_user2.ipynb
08/06/2025  01:30 PM             4,594 Introduction to data analysis.ipynb
07/14/2025  11:46 AM            66,188 Introduction to Python - 9th July .ipynb
07/21/2025  12:58 PM            74,377 Introduction to Python.ipynb
03/22/2025  05:55 AM         7,013,241 listings.csv
08/06/2025  01:28 PM                36 mailbox.csv
07/26/2025  11:15 AM        13,637,378 Mcdonalds data 2021-24.csv
07/26/2025  05:00 PM            62,512 Mcdonalds finanacial data 2021-2024.ipynb
07/26/2025  04:39 PM             7,558 mcdonalds_cleaned.csv
07/01/2025  09:34 PM             2,669 Mini Project.ipynb
08/06/2025  12:24 PM           186,310 Personal Tests.ipynb
07/23/2025  01:57 PM             7,357 Soil and and growing medium factor prediction2.ipynb
07/22/2025  01:30 PM            11,865 Soil and Growing Medium Factors Predictions.ipynb
05/09/2025  05:48 PM             8,512 SoloLearn.ipynb
07/12/2025  04:18 PM             2,915 Student profile assignment.ipynb
07/16/2025  05:37 PM            24,475 Tabular Data.ipynb
07/30/2025  02:09 PM    <DIR>          Takeout
07/18/2025  02:26 PM             5,922 Tomatoe Farm.ipynb
07/17/2025  10:24 PM             1,947 Untitled.ipynb
03/22/2025  06:01 AM        44,350,518 us_baby_names.csv
08/02/2025  10:06 PM         1,863,680 visualizing fintech user data.csv
03/27/2025  12:59 PM            84,623 Visualizing qualitative data.ipynb
07/16/2025  02:46 PM           186,382 Visualizing quantitative data.ipynb
06/18/2025  01:54 PM           525,187 water_potability.csv
06/23/2025  03:09 PM             4,440 Week 2 practice Assignment .ipynb
08/06/2025  12:27 PM            21,262 while_loop.ipynb
07/01/2025  05:16 PM            25,080 working_with_strings_in_python_30-06-25.ipynb
              40 File(s)    359,448,269 bytes
               4 Dir(s)  93,043,994,624 bytes free

### *Put the mbox into the variable*

In [8]:
mboxfile = "All mail Including Spam and Trash.mbox"

#### *Extract the file from the mbox file*

In [9]:
mbox = mailbox.mbox(mboxfile)
mbox

#### *Extract the keys inside the inbox file*

In [10]:
for key in mbox[0].keys():
    print(key)

X-GM-THRID
X-Gmail-Labels
Delivered-To
Received
X-Google-Smtp-Source
X-Received
ARC-Seal
ARC-Message-Signature
ARC-Authentication-Results
Return-Path
Received
Received-SPF
Authentication-Results
DKIM-Signature
DKIM-Signature
Received
Received
Content-Transfer-Encoding
Content-Type
Date
From
Mime-Version
Message-ID
Subject
X-SG-EID
X-SG-ID
To
X-Entity-ID

### Data Transformation

- The data isn't in a format that is usable

- The file format isn't usable

In [11]:
import csv

In [13]:
# Create a csv file with only the required attributes:
with open("mailbox.csv", "w") as outputfile:
    writer = csv.writer(outputfile)
    writer.writerow(["subject", "from", "date", "to", "label", "thread"])
    for message in mbox:
        writer.writerow([
            message["subject"], message["from"], message["date"],
            message["to"], message["X-Gmail-Labels"], message["X-GM-THRID"]
        ])

In [24]:
gmail_data = pd.read_csv("mailbox.csv")
gmail_data.head()

,subject,from,date,to,label,thread
0,I have a new paid survey for Sadiq! [Survey ...,Maria from KingOpinion <noreply@kingopinion.com>,"Wed, 30 Jul 2025 08:21:53 +0000 (UTC)",Sadiq Abdullahi <abdullerheepserdique@gmail.com>,"Inbox,Category Promotions,Unread",1839059399074785468
1,I have a new paid survey for Sadiq! [Survey ...,Maria from KingOpinion <noreply@kingopinion.com>,"Sat, 12 Jul 2025 17:04:14 +0000 (UTC)",Sadiq Abdullahi <abdullerheepserdique@gmail.com>,"Inbox,Category Promotions,Unread",1837461516665967277
2,Work in Slack with people outside your company,"""Slack"" <no-reply@email.slackhq.com>","Wed, 16 Jul 2025 10:13:09 -0600",<abdullerheepserdique@gmail.com>,"Inbox,Category Promotions,Unread",1837821000855859858
3,=?utf-8?q?New_HIV_variant_discovered_in_the_Ne...,Quora Digest <english-quora-digest@quora.com>,"Wed, 23 Jul 2025 15:40:05 +0000",abdullerheepserdique@gmail.com,"Inbox,Category Updates,Unread",1838452787687869506
4,Find out why work flows faster in Slack channels,"""Slack"" <no-reply@email.slackhq.com>","Fri, 27 Jun 2025 10:06:02 -0600",<abdullerheepserdique@gmail.com>,"Inbox,Category Promotions,Unread",1836098903748391710

In [25]:
gmail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6683 entries, 0 to 6682
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  6681 non-null   object
 1   from     6683 non-null   object
 2   date     6683 non-null   object
 3   to       6683 non-null   object
 4   label    6683 non-null   object
 5   thread   6683 non-null   int64
dtypes: int64(1), object(5)
memory usage: 313.4+ KB

In [26]:
gmail_data["date"].head(3)

0    Wed, 30 Jul 2025 08:21:53 +0000 (UTC)
1    Sat, 12 Jul 2025 17:04:14 +0000 (UTC)
2          Wed, 16 Jul 2025 10:13:09 -0600
Name: date, dtype: object

- Convert the data column from object to data time

In [27]:
gmail_data["date"] = gmail_data["date"].apply(lambda x: pd.to_datetime(x, errors = "coerce", utc = True ))

In [28]:
gmail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6683 entries, 0 to 6682
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  6681 non-null   object
 1   from     6683 non-null   object
 2   date     6683 non-null   datetime64[ns, UTC]
 3   to       6683 non-null   object
 4   label    6683 non-null   object
 5   thread   6683 non-null   int64
dtypes: datetime64[ns, UTC](1), int64(1), object(4)
memory usage: 313.4+ KB

### Refactor The Date Column